USE ROLE USERADMIN;

CREATE OR REPLACE USER cetpower
PASSWORD = 'power'
LOGIN_NAME = 'hopelyn'
FIRST_NAME = 'hopelyn'
LAST_NAME = 'okon'
EMAIL = 'okona4380@gmail.com'
MUST_CHANGE_PASSWORD = true
DEFAULT_WAREHOUSE = COMPUTE_WH;

USE ROLE SECURITYADMIN;

GRANT ROLE SYSADMIN TO USER cetpower;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

--exploring the users and roles in my account

USE ROLE ACCOUNTADMIN;

SHOW USERS;

